'use client';

import React, { useEffect, useState } from 'react';
import { useWorkflowStore } from '@/stores/workflowStore';
import { api } from '@/services/api';
import { 
  PlayCircle, 
  CheckCircle2, 
  XCircle, 
  Loader2, 
  Clock, 
  RefreshCw,
  Search,
  Zap,
  ChevronRight
} from 'lucide-react';

export default function GenerationJobsPage() {
  const { businessId } = useWorkflowStore();
  const [jobs, setJobs] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  const fetchJobs = async () => {
    if (!businessId) return;
    try {
      const res = await api.listGenerationJobs(businessId);
      if (res.success && res.data) {
        setJobs(res.data);
      }
    } catch (e) {
      console.error(e);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchJobs();
    const interval = setInterval(fetchJobs, 5000); // Poll for live jobs
    return () => clearInterval(interval);
  }, [businessId]);

  const getStatusBadge = (status: string) => {
    const map: Record<string, string> = {
      queued: 'bg-slate-100 text-slate-700 border-slate-200',
      running: 'bg-blue-100 text-blue-800 border-blue-200',
      validating: 'bg-purple-100 text-purple-800 border-purple-200',
      completed: 'bg-emerald-100 text-emerald-800 border-emerald-200',
      failed: 'bg-rose-100 text-rose-800 border-rose-200',
    };
    return map[status.toLowerCase()] || 'bg-slate-100 text-slate-700';
  };

  const getStatusIcon = (status: string) => {
    const map: Record<string, any> = {
      queued: <Clock className="w-4 h-4 text-slate-400" />,
      running: <Loader2 className="w-4 h-4 text-blue-500 animate-spin" />,
      validating: <Zap className="w-4 h-4 text-purple-600 animate-pulse" />,
      completed: <CheckCircle2 className="w-4 h-4 text-emerald-600" />,
      failed: <XCircle className="w-4 h-4 text-rose-600" />,
    };
    return map[status.toLowerCase()] || <Clock className="w-4 h-4 text-slate-400" />;
  };

  const displayJobs = jobs;

  return (
    <div className="flex-1 p-8 flex flex-col gap-6 bg-slate-50/50">
      {/* Header */}
      <div className="flex justify-between items-center">
        <div>
          <h2 className="font-outfit font-bold text-xl text-slate-900">Generation Jobs log</h2>
          <p className="text-xs text-slate-500 mt-1">Monitor the compilation workflow portfolios generated by FlowCore AI Generator pipeline.</p>
        </div>
        <button
          onClick={fetchJobs}
          className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-white border border-slate-200 text-xs font-semibold text-slate-600 hover:bg-slate-50 cursor-pointer shadow-sm transition-all"
        >
          <RefreshCw className="w-3.5 h-3.5" /> Refresh List
        </button>
      </div>

      {loading && jobs.length === 0 ? (
        <div className="flex-1 flex flex-col items-center justify-center p-8 text-slate-400">
          <Loader2 className="w-6 h-6 text-emerald-600 animate-spin mb-2" />
          <span className="text-xs font-semibold">Loading generation jobs...</span>
        </div>
      ) : (
        <div className="bg-white border border-slate-200 rounded-xl shadow-sm overflow-hidden flex-1 flex flex-col">
          <div className="p-4 border-b border-slate-100 flex items-center justify-between">
            <h3 className="text-xs font-bold text-slate-505 uppercase tracking-wider flex items-center gap-1.5">
              <PlayCircle className="w-4 h-4 text-emerald-600" /> Pipeline Jobs History
            </h3>
          </div>

          <div className="flex-1 overflow-x-auto">
            <table className="w-full text-left border-collapse">
              <thead>
                <tr className="border-b border-slate-100 bg-slate-50/50 text-[10px] font-bold text-slate-400 uppercase tracking-wider font-mono">
                  <th className="p-4">Job Info / Prompt</th>
                  <th className="p-4">Packs / Category</th>
                  <th className="p-4">Status & Progress</th>
                  <th className="p-4">Timings</th>
                  <th className="p-4">Outcome</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100 text-xs text-slate-700">
                {displayJobs.length === 0 ? (
                  <tr>
                    <td colSpan={5} className="p-8 text-center text-slate-400">
                      No generation jobs found. Trigger one in the AI Builder!
                    </td>
                  </tr>
                ) : (
                  displayJobs.map((j) => (
                    <tr key={j.id} className="hover:bg-slate-50/20 transition-colors">
                    <td className="p-4">
                      <div className="flex flex-col gap-1 max-w-md">
                        <span className="font-bold text-slate-800 break-words">{j.input_description}</span>
                        <span className="text-[9px] text-slate-400 font-mono">Job ID: {j.id}</span>
                      </div>
                    </td>
                    <td className="p-4">
                      <div className="flex flex-col gap-1">
                        <div className="flex gap-1 flex-wrap">
                          {(j.input_packs || []).map((pack: string) => (
                            <span key={pack} className="px-1.5 py-0.5 bg-slate-100 border border-slate-200 rounded text-[8px] font-bold text-slate-600">
                              {pack}
                            </span>
                          ))}
                        </div>
                        {j.category && (
                          <span className="text-[10px] text-emerald-700 font-bold capitalize">
                            Category: {j.category}
                          </span>
                        )}
                      </div>
                    </td>
                    <td className="p-4">
                      <div className="flex flex-col gap-1.5">
                        <div className="flex items-center gap-1.5 font-bold uppercase tracking-wider text-[10px]">
                          {getStatusIcon(j.status)}
                          <span className={`px-2 py-0.5 border rounded-full ${getStatusBadge(j.status)}`}>
                            {j.status}
                          </span>
                        </div>
                        {/* Progress Bar */}
                        <div className="w-24 bg-slate-100 rounded-full h-1.5 overflow-hidden">
                          <div 
                            className={`h-full rounded-full transition-all duration-500 ${
                              j.status === 'failed' ? 'bg-rose-500' : 'bg-emerald-500'
                            }`}
                            style={{ width: `${j.progress}%` }}
                          />
                        </div>
                      </div>
                    </td>
                    <td className="p-4 font-semibold font-mono text-[9px] text-slate-400">
                      <div className="flex flex-col gap-0.5">
                        <span>Created: {new Date(j.created_at).toLocaleTimeString()}</span>
                        {j.completed_at && (
                          <span>Finished: {new Date(j.completed_at).toLocaleTimeString()}</span>
                        )}
                      </div>
                    </td>
                    <td className="p-4">
                      {j.status === 'failed' ? (
                        <div className="text-[10px] text-rose-600 font-medium max-w-xs break-words border border-rose-100 bg-rose-50/20 p-2 rounded-lg">
                          Error: {j.error || 'Unknown failure'}
                        </div>
                      ) : j.status === 'completed' ? (
                        <div className="text-[10px] text-emerald-700 font-bold flex flex-col gap-0.5">
                          <span>Method: <strong className="uppercase">{j.method || 'AI'}</strong></span>
                          <span className="text-slate-400 font-medium">Successfully deployed to portfolio.</span>
                        </div>
                      ) : (
                        <span className="text-[10px] text-slate-400 italic">Processing pipeline...</span>
                      )}
                    </td>
                  </tr>
                )))}
              </tbody>
            </table>
          </div>
        </div>
      )}
    </div>
  );
}
